feat: fonts generator
atls/figma pull request #11
Opened 2022-09-22 12:40 UTC by brusselboy

2022-09-22 14:12 UTC, TFK70 requested changes

2022-09-22 14:12 UTC, TFK70 commented on theme/theme-fonts-generator/package.json
> +    "figma-js": "^1.16.0"
Тебе обязательно нужно поставить её в peerDependencies. Как тогда он будет брать весрию figma-js на проекте?

Пофикси во всех остальных местах, если там так же

2022-09-22 14:12 UTC, TFK70 commented on theme/theme-fonts-generator/package.json
> +    "@atls/figma-theme-generator-common": "workspace:0.0.1",
Здесь аналогично. Если эта зависимость есть в бандле - она должна быть и в пирах. Если она используется только в тестах, например, то так и оставь в девах

2022-09-23 08:43 UTC, TFK70 approved these changes

2022-09-26 15:48 UTC, TorinAsakura approved these changes

2022-09-26 15:49 UTC, merged