Feat/theme
atls/figma pull request #2
Opened 2022-02-07 15:29 UTC by TorinAsakura

2022-04-05 11:41 UTC, TorinAsakura commented on assets/assets-cli/package.json
>      "build": "builder build plugin",
используй library build вместо

2022-09-19 16:37 UTC, TFK70 requested changes
@brusselboy покрой все это дело unit тестами. Пример организации тестов и тестирования генераторов можешь чекнуть [тут](https://github.com/atls/uikit/tree/master/generators/button/src/unit)

2022-09-20 16:33 UTC, TFK70 requested changes
У тебя после запуска тестов появляется мусорный файл в репе. Засунь ее в папку с тестами, а лучше вообще в гитигнор

2022-09-20 16:35 UTC, brusselboy commented
> У тебя после запуска тестов появляется мусорный файл в репе. Засунь ее в папку с тестами, а лучше вообще в гитигнор

ты про fontSizes.ts который генерится?

2022-09-20 17:11 UTC, TFK70 requested changes
Тебе все-равно нужно класть этот файл в папку с тестами, не засоряй общий скоуп мусором от тестов

И добавь пока рендомный второй тест чтобы они запускались

2022-09-21 14:06 UTC, merged