Feat/theme generator improvement
atls/figma pull request #29
Opened 2024-06-13 22:26 UTC by aliceinapple

- Добавила возможность добавлять страницы в игнор (указывая их id)
- Добавила возможность генерировать тему только с определенной страницы (тоже по id)
- Добавила возможность указывать префикс, чтобы в генерации учавствовали только определенные узлы
___
- Нейминги для радиусов и высоты линии сделала по аналогии с размерами шрифтов
- Нейминги для теней, шрифтов и весов шрифтов оставила как есть (для весов и самих шрифтов нейминги вроде как логичные, на счет теней вопрос, сейчас у них нейминги генерируются в соответствии с цветом)
___
Структура для кнопок и инпутов
Посмотрела несколько вариантов разных макетов и сделала генерацию структуры в цветах для кнопок и инпутов в соответствии с графой "Архив" в ридми, это будет самый удобный вариант для генерации

2024-06-14 05:54 UTC, Nelfimov requested changes
Отличная работа!

Давай попробуем перевести все в ESM, а так же покрыть тестами. Я вижу так:
- либо покрываем тестом каждую функцию класс (юнит тесты)
- либо в качестве теста прогоняем генератором какой нибудь дизайн старого проекта (напр. drum-in), делаем снэпшот (можно в виде строки значений каждого объекта) и сравниваем с ним (интеграционный). Примеры можешь посмотреть в гиперионе генераторе или тулзах.

В идеале сделать оба варианта, но если уйдет много времени - давай что-то одно сделаем.

2024-06-14 05:54 UTC, Nelfimov commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-remote.cjs
давай сюда добавим

1. `preferReuse`
2. `defaultSemver...: '''`

2024-06-14 05:54 UTC, Nelfimov commented on package.json
> +    "typescript": "4.9.5"
можно 5.2.2

2024-06-16 22:05 UTC, aliceinapple commented
@Nelfimov 

После перехода на ESM, когда запускаю скрипт - получаю ошибку:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/macbookair15/WebstormProjects/figma/theme/theme-cli/src/index.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async nextLoad (node:internal/modules/esm/hooks:750:22)
    at async Hooks.load (node:internal/modules/esm/hooks:383:20)
    at async handleMessage (node:internal/modules/esm/worker:199:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

Пробовала также разные другие скрипты, например такой ```node --loader ts-node/esm src/index.ts```, получаю другую ошибку:

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: Cannot find package 'commander' imported from /Users/macbookair15/WebstormProjects/figma/theme/theme-cli/src/index.ts
    at packageResolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757:9)
    at moduleResolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:168:34)
    at /Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:750:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:238:30)

Node.js v21.7.3
```

2024-06-16 22:12 UTC, TorinAsakura commented
@aliceinapple Ноду откати на 19

2024-06-17 07:50 UTC, aliceinapple commented
@TorinAsakura @Nelfimov 
> @aliceinapple Ноду откати на 19

Все равно остается проблема с импортом пакетов (пробовала еще 18 ноду)

```
/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
CustomError: Cannot find package 'commander' imported from /Users/macbookair15/WebstormProjects/figma/theme/theme-cli/src/index.ts
    at packageResolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:757:9)
    at moduleResolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:168:34)
    at /Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/esm.ts:197:12)
    at resolve (/Users/macbookair15/WebstormProjects/figma/.yarn/__virtual__/ts-node-virtual-1eb244db5c/0/cache/ts-node-npm-10.9.2-3f3890b9ac-a91a15b3c9.zip/node_modules/ts-node/src/child/child-loader.ts:15:39)
    at nextResolve (node:internal/modules/esm/hooks:654:28)
macbookair15@MacBook-Air-Macbook theme-cli % node -v
v19.9.0
```

2024-06-17 09:34 UTC, Nelfimov commented
@aliceinapple добавил новый скрипт на `swc`. Так же пришлось бампнуть `commander`. Проверено на 22 ноде. Для 19 придется менять `--import swc-node/register/esm-register` на `--loader swc-node/register/esm`

2024-06-17 16:57 UTC, merged