Feat/fragments generator
atls/figma pull request #41
Opened 2024-12-02 21:30 UTC by Amiditin

Resolves https://github.com/atls/figma/issues/40

2024-12-16 08:32 UTC, Nelfimov requested changes
не хватает ридми с примером правильной структуры дизайна

2024-12-16 08:32 UTC, Nelfimov commented on .gitignore
> +.yarn/sdks
это можешь не отключать

2024-12-16 08:32 UTC, Nelfimov commented on utils/file/package.json
> +  "main": "src/index.ts",
добавь `exports`

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-cli/package.json
> +  "main": "src/index.ts",
`exports`

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-cli/package.json
> +    "generate-fragments-new": "node --import @swc-node/register/esm-register src/index.ts",
оставь какой-то один из этих скриптов

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-cli/src/run.ts
> +import assert                           from 'node:assert'
`node:assert/strict`

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-cli/src/run.ts
> +import { join }                         from 'path'
`node:path`

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-cli/src/index.ts
> +import logger              from 'npmlog'
используй https://www.npmjs.com/package/pino

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-cli/src/index.ts
> +    if (!id || id === '') throw Error('ID must not be empty')
вроде условие `id === '''` покрывается проверкой `!id`, проверь

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-generator/package.json
> +  "main": "src/index.ts",
`exports`

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-generator/src/figma-fragments.generator.ts
> +      export const GeneratedFragment = memo(() => (${fragment}))`
давай добавим генерацию `displayName` либо использовать не стрелочную функцию (хотя это менее чисто)

2024-12-16 08:32 UTC, Nelfimov commented on fragments/fragments-generator/src/strategy/tests/create-box.test.ts
> +import { Frame }             from 'figma-js'
юнит тесты лучше держать рядом с файлами. Напр `create-bot.strategy.test.ts`

2024-12-17 06:15 UTC, Nelfimov commented on utils/file/package.json
> +  "main": "src/index.ts",
проверь tsconfig:

https://github.com/atls/figma/actions/runs/12355302827/job/34478619323#step:9:36

2024-12-17 06:23 UTC, Nelfimov requested changes

2024-12-17 06:23 UTC, Nelfimov commented on README.md
> +## Генератор фрагментов
этого достаточно? Никаких доп. требований к дизайну?

2024-12-17 06:23 UTC, Nelfimov commented on fragments/fragments-cli/package.json
> +    "generate-fragments": "node --import @swc-node/register/esm-register src/index.ts",
можно еще так попробовать:
`node --experimental-strip-types --experimental-transform-types src/index.ts`

2024-12-17 06:23 UTC, Nelfimov commented on fragments/fragments-cli/src/index.ts
> +const logger = pino({
тут можешь взять мои настройки из проекта:

https://github.com/rees46/web/blob/stage/apps/robot/src/logger/logger.ts#L11:L25

2024-12-17 06:23 UTC, Nelfimov commented on fragments/fragments-generator/src/figma-fragments.generator.ts
> +      export const GeneratedFragment = memo(() => (${fragment}))`
не увидел что сделал. В `react-dev` расширении сгенерированный фрагмент все равно будет анонимным потому что в `memo` - стрелочная функция

2024-12-17 09:12 UTC, Amiditin commented on fragments/fragments-generator/src/figma-fragments.generator.ts
> +      export const GeneratedFragment = memo(() => (${fragment}))`
> не увидел что сделал. В `react-dev` расширении сгенерированный фрагмент все равно будет анонимным потому что в `memo` - стрелочная функция

Добавил опции для имени фрагмента e47ec73, сейчас понял что имелось в виду. Не помню чтобы где либо это использовали, но можно добавить

2024-12-17 09:16 UTC, Nelfimov commented on fragments/fragments-generator/src/figma-fragments.generator.ts
> +      export const GeneratedFragment = memo(() => (${fragment}))`
давай добавим - будет проще в дебаге

2024-12-17 09:18 UTC, Amiditin commented on README.md
> +## Генератор фрагментов
> этого достаточно? Никаких доп. требований к дизайну?

Да, пока не думаю, что дизайн нужно как-то модифицировать, ориентировался на рис, и типизацию `figma-js`. Из чего то особенного только название компонента должно быть в название ноды у инстансов, как для `Button` или `Input`.

2024-12-17 09:18 UTC, Nelfimov commented
Дополнительным ПРом к этому сделай пожалуйста бамп `yarn` бандла

2024-12-17 09:19 UTC, Nelfimov commented on README.md
> +## Генератор фрагментов
Давай и это добавим - нужно ориентироваться на ситуацию, когда к нам пришел новый дизайнер либо мы просим чужих дизайнеров поправить фигму для нас.

2024-12-17 09:24 UTC, Amiditin commented on README.md
> +## Генератор фрагментов
> Давай и это добавим - нужно ориентироваться на ситуацию, когда к нам пришел новый дизайнер либо мы просим чужих дизайнеров поправить фигму для нас.

В абзатце предложение упоминаю это:

> с условием, что в название ноды есть имя создаваемого фрагмента, например `Pattern/Button`.

2024-12-17 09:43 UTC, Nelfimov commented on fragments/fragments-cli/package.json
> +    "generate-fragments": "node --import @swc-node/register/esm-register src/index.ts",
Тут либо менять расширение импорта run.js на run.ts либо отказываться от этой идеи. Если поменяешь расширение - протестируй билд обязательно

2024-12-18 00:25 UTC, Amiditin commented on fragments/fragments-cli/package.json
> +    "generate-fragments": "node --import @swc-node/register/esm-register src/index.ts",
> tsc src/index.ts --outDir dist

не понял как это сделать во время выполнения ноды, в src файлах и так run.ts

2024-12-18 00:26 UTC, Amiditin commented on utils/file/package.json
> +  "main": "src/index.ts",
Добавлял `rootDir` ошибка оставалась, попробую после бампа yarn ещё раз, пока что убрал

2024-12-18 05:06 UTC, Nelfimov commented on fragments/fragments-cli/package.json
> +    "generate-fragments": "node --import @swc-node/register/esm-register src/index.ts",
`import * from 'run.ts'`

Если используешь эти флаги что я указал, то надо указывать явно расширение ts в импорте. Но тогда у нас библиотека не соберется, поэтому отбой

2024-12-18 05:07 UTC, Nelfimov approved these changes

2024-12-18 05:07 UTC, merged